### ISSUE TITLE
Parse shutdown

### ISSUE THREAD

**Issue by chrissearle** [javaBin/ems-ios#161]
Parse.com is shutting down. Need to remove integration and find an alternative APNS system (we only used parse to provide the server component for remote notifications).

**Comment by bendiksolheim** [comment]
There are a number of these services, but I have used https://www.pushwoosh.com/ on a project at work and that was decent enough.

**Comment by bendiksolheim** [comment]
.. unless you actually have some logic on that server? Or was it just used to push the notifications?

**Comment by chrissearle** [comment]
Just for push. Need a server that supports apple's APNS system and has a plugin for the app - a JSON api would also be "nice to have". Never used anything else parse had - just wanted a free push server.

**Comment by bendiksolheim** [comment]
We used pushwoosh just for the push stuff. They had a library we just included in our app, and everything sort of worked out of the box. There are multiple other similar services as well, I believe.

**Comment by chrissearle** [comment]
Yep - I expect that things have moved on since we originally added push. Haven't had a chance to look around yet.

**Comment by chrissearle** [comment]
puswhoosh free is limited to 1000000 devices - how will we ever cope? ;)

**Comment by chrissearle** [comment]
Found a comparison (july 2015) - a little out of date.

Pushwoosh is looking good for our size/numbers.

**Comment by chrissearle** [comment]
Pushwoosh implemented. Free version doesn't give API access - so any push messages I'll have to log in to pushwoosh - but otherwise it's just as good. Considered complete.
