### ISSUE TITLE
Support new talk lengths

### ISSUE THREAD

**Issue by Espenhh** [javaBin/ems-ios#162]
For JavaZone 2016 there has been introduced a few new talk formats.

* Lightning talks: 10 minutes and 20 minutes
* Presentations: 45 minutes and 60 minutes

The talks for 2016 has been published now, but the slots are not assigned yet. The slot list is also empty, but will be created soon. Assigning each talk to each slot and room will be done later this year.

As of now, the app in the app store are not working. Will everything start to work when the slot list is created? The algorithm for the slots probably needs to be checked to make sure that everything works.

**Comment by chrissearle** [comment]
Right now the app will assign a single slot to each talk based on the EMS slot data - but this is just the slot that has the start/end of the actual session.

It then will do some really hairy logic - https://github.com/javaBin/ems-ios/blob/master/EMS/CoreData%20Model/EMSModel.m#L968-L1027 - to group lightning talks under a main slot (where the main slot is a slot of a full hour presentation). This just sets the slot "name" - this is the name that is used to group by in the list view _only_.

The 10 and 20 min talks should work. I have no idea how the 45 will work - they may end up placed grouped as if they were lightning slots or they may end up not grouped - I don't know.

Oddly - all sessions without a slot allocated should get the name "Time slot not yet allocated" and not a lot of time data in detail view - is this not  working?

Don't think we've tested it without the overall slots list present.

**Comment by Espenhh** [comment]
> Don't think we've tested it without the overall slots list present.
That's probably why it doesn't work right now. @anders88 will populate this list soon, so hopefully the "Time slot not yet allocated" will work like a charm then :)

We can probably assign some talks to time slots in production as a test when the slots are available, since that will not be visible on the web pages yet, we can do that as a test. We'll try to coordinate some testing one of the next Tuesdays :)

Sorry about all this confusion, and the late notice. It's kind'of become a tradition now (a bad one, yeah, but a tradition nonetheless... 🙃)
